### PR TITLE
add light and dark themes

### PR DESCRIPTION
**Pull request by theavege**
Hi. I add light (from [tigervnc](https://tigervnc.org/)) and dark (from [mrv2](https://mrv2.sourceforge.io/)) themes.

### CODE REVIEW

**Comment by geri1701** [comment]
Hi,

Thank you for this contribution! Before we can merge this pull request, we need to address some concerns:

- The light theme from [tigervnc](https://tigervnc.org/) is licensed under GPL-2.0, which requires that niccalc be licensed under GPL-2.0 if we include it.
- The dark theme from [mrv2](https://mrv2.sourceforge.io/) is licensed under the BSD-3-Clause, which is generally permissive.

To proceed, we need to ensure that integrating these themes does not conflict with our project's current license. Could you please provide more details on how these themes will be integrated and confirm their compatibility with our project's licensing?

Thank you for your understanding and cooperation!

Best regards,
Geri

**Comment by theavege** [comment]
I didn't take them from the code.
I picked the colors from the screenshot.
What license are we talking about?
They both use colors from Adwaita.

I added a visual design similar to these programs, but based on [this one](https://fltk-rs.github.io/fltk-book/Styling.html#global-styling).

**Comment by geri1701** [comment]
Sorry, then I misunderstood you. Thank you for clarifying that!

**Review by geri1701 — APPROVED** [review]

**Comment by theavege** [comment]
No problem. Thank you for asking.
Did you like the design?
My goal is to share experiences.
It's a rare thing that you wanted to communicate.

**Comment by geri1701** [comment]
Yes I like your new design and themes, especially the dark one.  I also think the right-click menu is a perfect solution. 

When it comes to exchanging experiences, I think emails are very suitable.

**Pull request merged**
